SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (12, N'Fire 7"', N'Beautiful 7" IPS display (171 ppi / 1024 x 600)', N'Tablets', CAST(49.99 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (13, N'Fire TV Stick', N'Just plug in and start streaming in minutes. Take it from room to room and turn your HDTVs into streaming media centres.', N'Set-top boxes', CAST(34.99 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (14, N'All-new Kindle Paperwhite', N'Unsurpassed high-resolution 300 ppi display - reads like real paper', N'E-readers', CAST(109.99 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (15, N'[Apple MFI Certified] Anker Lightning to USB Cable 3ft / 0.9m', N'The Anker Advantage: Join the 10 million+ powered by Amazon''s #1 charging brand.', N'USB Cables', CAST(5.21 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (16, N'AmazonBasics AA Performance Alkaline Batteries [Pack of 48]', N'Pack of 48 AA Alkaline 1.5 Volt Batteries', N'Disposable Batteries', CAST(12.99 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (17, N'TomTom Start 25 5-Inch Sat Nav with Western Europe Maps & Lifetime Map Updates', N'FREE Lifetime Maps - Always drive with the latest map.', N'Sat-navs', CAST(97.00 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (18, N'GoPro HERO4 Camera - Adventure Edition (English-French Language), Silver', N'Built-In Touch Display: Frame your shots. Easily adjust settings. Play back videos and photos. Improved Camera Control: New dedicated button enables quick access to camera settings. Simplified menus make navigating settings easier than ever.', N'Action Cameras', CAST(250.00 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (19, N'CR2032 Battery (2 pack) - Panasonic, Lithium Coin Cell, 3V', N'CR2032 lithium button cells are commonly used in car security (car alarm/keyfob batteries)', N'Disposable Batteries', CAST(0.97 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (20, N'Sony DVP-SR170 DVD Player', N'A DVD player with multi-playback including multi-format discs and CDs', N'DVD Players', CAST(24.99 AS Decimal(16, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price]) VALUES (21, N'Mpow Swift Outdoor Sport Bluetooth Wireless Stereo Headphone - Cyan', N'Mpow Brand Certified: Top-Brand Bluetooth Accessories for Smartphones', N'Headsets', CAST(16.09 AS Decimal(16, 2)))
SET IDENTITY_INSERT [dbo].[Products] OFF
